name: Eleventy Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vanilla-pattern-library
        uses: actions/checkout@v4

      - run: rm -rf vanilla-web-assets

      - name: Checkout vanilla-web-assets
        uses: actions/checkout@v4
        with:
          repository: 'ndorfin/vanilla-web-assets'
          ref: 'main'
          sparse-checkout: src
          path: 'vanilla-web-assets'
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - run: ls vanilla-web-assets/src

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '20.12.2'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci

      - run: npm run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
